prompt --install
exec apex_util.SET_SECURITY_GROUP_ID(4603234547011432);
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/css_dark_custom_styles_css.sql
@@application/shared_components/files/fonts_font_css.sql
@@application/shared_components/files/fonts_poppins_700_eot.sql
@@application/shared_components/files/fonts_poppins_700_svg.sql
@@application/shared_components/files/fonts_poppins_700_ttf.sql
@@application/shared_components/files/fonts_poppins_700_woff.sql
@@application/shared_components/files/fonts_poppins_700_woff2.sql
@@application/shared_components/files/fonts_poppins_regular_eot.sql
@@application/shared_components/files/fonts_poppins_regular_svg.sql
@@application/shared_components/files/fonts_poppins_regular_ttf.sql
@@application/shared_components/files/fonts_poppins_regular_woff.sql
@@application/shared_components/files/fonts_poppins_regular_woff2.sql
@@application/shared_components/files/js_helper_js.sql
@@application/shared_components/files/fonts_font_min_css.sql
@@application/shared_components/files/js_webcomponents_c_ticker_js.sql
@@application/shared_components/files/css_dark_custom_styles_min_css.sql
@@application/shared_components/files/js_webcomponents_c_ticker_min_js.sql
@@application/shared_components/files/js_helper_min_js.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/is_active.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/builder.sql
@@application/shared_components/plugins/template_component/tc_yaaa_conversation_history.sql
@@application/shared_components/plugins/template_component/dev_jnmr_floating_button.sql
@@application/shared_components/plugins/template_component/dev_progress_tracker.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00050.sql
@@application/pages/page_00055.sql
@@application/pages/page_00100.sql
@@application/pages/page_00110.sql
@@application/pages/page_00200.sql
@@application/pages/page_00250.sql
@@application/pages/page_00300.sql
@@application/pages/page_00305.sql
@@application/pages/page_00310.sql
@@application/pages/page_00320.sql
@@application/pages/page_02000.sql
@@application/pages/page_03000.sql
@@application/pages/page_05000.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
