-- create tables

create table ai_services (
    ai_service_id             number generated by default on null as identity
                   constraint ai_services_ai_service_id_pk primary key,
    name           varchar2(255 char) not null,
    identifier     varchar2(30 char) not null,
    description    varchar2(4000 char),
    base_url       varchar2(255 char) not null,
    model          varchar2(200 char) not null
);


create table ai_service_additional_headers (
    ai_service_additional_header_id               number generated by default on null as identity
                     constraint ai_service_additional_headers_ai_service_additional_header_id_pk primary key,
    ai_service_id    number                     constraint ai_service_additional_headers_ai_service_id_fk
                     references ai_services,
    header_name      varchar2(50 char) not null,
    header_value     varchar2(400 char) not null
);

-- table index
create index ai_service_additional_headers_i1 on ai_service_additional_headers (ai_service_id);


create table ai_service_custom_endpoints (
    ai_service_custom_endpoint_id               number generated by default on null as identity
                     constraint ai_service_custom_endpoints_ai_service_custom_endpoint_id_pk primary key,
    ai_service_id    number                     constraint ai_service_custom_endpoints_ai_service_id_fk
                     references ai_services,
    code             varchar2(50 char),
    endpoint         varchar2(400 char)
);

-- table index
create index ai_service_custom_endpoints_i1 on ai_service_custom_endpoints (ai_service_id);



create table ai_tools (
    ai_tool_id                     number generated by default on null as identity
                           constraint ai_tools_ai_tool_id_pk primary key,
    name                   varchar2(255 char) not null,
    description            varchar2(4000 char),
    identifier             varchar2(30 char) not null,
    function_name          varchar2(255 char) not null,
    parameters             clob not null,
    parameters_required    varchar2(4000 char) not null
);



create table ai_agents (
    ai_agent_id                      number generated by default on null as identity
                            constraint ai_agents_ai_agent_id_pk primary key,
    ai_service_id           number                            constraint ai_agents_ai_service_id_fk
                            references ai_services,
    name                    varchar2(255 char) not null,
    description             varchar2(4000 char),
    system_prompt           clob,
    developer_prompt        clob,
    examples                clob,
    default_history_mode    varchar2(4000 char) constraint ai_agents_default_history_mode_ck
                            check (default_history_mode in ('TABLE','COLLECTION'))
);

-- table index
create index ai_agents_i1 on ai_agents (ai_service_id);


create table ai_agent_tools (
    ai_agent_tool_id             number generated by default on null as identity
                   constraint ai_agent_tools_ai_agent_tool_id_pk primary key,
    ai_agent_id    number                   constraint ai_agent_tools_ai_agent_id_fk
                   references ai_agents,
    ai_tool_id     number                   constraint ai_agent_tools_ai_tool_id_fk
                   references ai_tools
);

-- table index
create index ai_agent_tools_i1 on ai_agent_tools (ai_agent_id);

create index ai_agent_tools_i2 on ai_agent_tools (ai_tool_id);



create table ai_conversations (
    ai_conversation_id                number generated by default on null as identity
                      constraint ai_conversations_ai_conversation_id_pk primary key,
    ai_agent_id       number                      constraint ai_conversations_ai_agent_id_fk
                      references ai_agents not null,
    ai_service_id     number                      constraint ai_conversations_ai_service_id_fk
                      references ai_services not null,
    creation_ts       timestamp with time zone not null,
    model             varchar2(200 char) not null,
    tools             clob,
    execution_type    varchar2(30 char) not null constraint ai_conversations_execution_type_ck
                      check (execution_type in ('USER','SYSTEM')),
    history_mode      varchar2(4000 char) not null constraint ai_conversations_history_mode_ck
                      check (history_mode in ('TABLE','COLLECTION')),
    status            varchar2(30 char) not null constraint ai_conversations_status_ck
                      check (status in ('CREATED','RUNNING','FINISHED','USER_QUESTION','MAX_MESSAGES_REACHED'))
);

-- table index
create index ai_conversations_i1 on ai_conversations (ai_agent_id);

create index ai_conversations_i2 on ai_conversations (ai_service_id);



create table ai_conversation_histories (
    ai_conversation_history_id                    number generated by default on null as identity
                          constraint ai_conversation_histories_ai_conversation_history_id_pk primary key,
    ai_conversation_id    number                          constraint ai_conversation_histories_ai_conversation_id_fk
                          references ai_conversations not null,
    creation_ts           timestamp with time zone not null,
    msg_type              varchar2(20 char) not null constraint ai_conversation_histories_msg_type_ck
                          check (msg_type in ('MESSAGE','EXCEPTION')),
    msg_direction         varchar2(5 char) not null constraint ai_conversation_histories_msg_direction_ck
                          check (msg_direction in ('IN','OUT')),
    msg_role              varchar2(200 char) constraint ai_conversation_histories_msg_role_ck
                          check (msg_role in ('SYSTEM','DEVELOPER','USER','ASSISTANT','TOOL')),
    content               clob
);

-- table index
create index ai_conversation_histories_i1 on ai_conversation_histories (ai_conversation_id);



-- Generated by Quick SQL 1.2.9 14/12/2025, 17:56:18

/*
ai_services
    name /nn
    identifier vc(30) /nn
    description
    base_url vc(255) /nn
    model vc(200) /nn
    ai_service_additional_headers
	    header_name vc(50) /nn
	    header_value vc(400) /nn
    ai_service_custom_endpoints
	    code  vc(50)
	    endpoint vc(400)
ai_tools
    name /nn
    description
    identifier vc(30) /nn
    function_name /nn
    parameters clob /nn
    parameters_required vc(4000) /nn
ai_agents
    name /nn
    description  
    system_prompt clob
    developer_prompt clob
    examples clob
    ai_service_id /fk ai_services 
    default_history_mode /check TABLE,COLLECTION
    ai_agent_tools
        ai_tool_id /fk ai_tools
ai_conversations
    creation_ts tstz /nn 
    ai_agent_id /nn /fk ai_agents
    ai_service_id /nn /fk ai_services
    model /nn vc(200)
    tools clob
    execution_type /nn vc(30) /check USER,SYSTEM
    history_mode /nn /check TABLE,COLLECTION
    status vc(30) /nn /check CREATED,RUNNING,FINISHED,USER_QUESTION,MAX_MESSAGES_REACHED
ai_conversation_histories
    creation_ts tstz /nn
    ai_conversation_id /nn /fk ai_conversations
    msg_type vc(20) /nn /check MESSAGE,EXCEPTION 
    msg_direction vc(5) /nn /check IN,OUT
    msg_role vc(200) /check SYSTEM,DEVELOPER,USER,ASSISTANT,TOOL
    content clob

 Non-default options:
# settings = {"apex":"Y","db":"23","pk":"IDENTITY","prefixpkwithtname":"Y"}

*/